Acquirer:
  connection: chinaums
  tableName: acquirer
  columns:
    id:
      type: string(10)
      primary: true
      autoincrement: false
    name:
      type: string(255)
    account:
      type: string(255)
    mcc_prefix:
      type: string(7)
    account_regex:
      type: string(64)
  relations:
    Merchant:
      local: id
      foreign: acquirer_id
      type: many  
###################################      
Branch:
  connection: chinaums
  tableName: branch
  columns:
    id: 
      type: integer(8)
      primary: true
      autoincrement: true
    acquirer_id:
      type: string(10)
    name:
      type: string(255)
  relations:
    Acquirer:
      local: acquirer_id
      foreign: id
      type: one       
###################################
Merchant:
  connection: chinaums
  tableName: merchant
  columns:
    id:
      type: integer(8)
      primary: true
      autoincrement: true
    code:
      type: string(15)
      autoincrement: false
    name:
      type: string(255)
    address:
      type: string(255)
    legal_person:
      type: string(255)
    license_no:
      type: string(15)
    tax_no:
      type: string(20)
    id_card:
      type: string(18)
    contact:
      type: string(255)
    acquirer_id:
      type: string(10)
    branch:
      type: string(255)
    account:
      type: string(255)
    mcc:
      type: string(4)
    rate:
      type: string(20)
    post:
      type: string(6)
    is_change_acquirer:
      type: boolean
    is_guarantee:
      type: boolean
    is_discount:
      type: boolean
    is_comfirm_risk:
      type: boolean
    is_close_creditcard:
      type: boolean
    draft:
      type: boolean
      default: false 	  
    create_date:
      type: datetime
    send_date:
      type: date(25)
    receive_date:
      type: date(25)
    comment: 
      type: string(255)
    export_to_oss: 
      type: boolean
    export_to_unionpay:
      type: boolean
    upload_scan_file: 
      type: boolean
    export_to_excel:
      type: boolean
    new_one:
      type: boolean
  relations:
    Acquirer:
      local: acquirer_id
      foreign: id
      type: one
    Terminal:
      local: id
      foreign: merchant_id
      type: many
###################################
Terminal:
  connection: chinaums
  tableName: terminal
  columns:
    id:
      type: integer(8)
      primary: true
      autoincrement: true
    merchant_id:
      type: integer(8)
    terminal_no:
      type: string(8)
  relations:
    Merchant:
      local: merchant_id
      foreign: id
      type: one
###################################       
Mcc:
  connection: chinaums
  tableName: mcc
  columns:
    id: 
      type: integer(8)
      primary: true
      autoincrement: true
    description: string(255)
    mcc: string(255)
    rate: string(255)          