<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Model_Acquirer', 'chinaums');

/**
 * Model_Base_Acquirer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $bank_name
 * @property string $acquirer_account
 * @property string $acquirer_code
 * @property string $mcc_prefix
 * @property string $account_regex
 * @property Doctrine_Collection $Merchant
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author      <>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Acquirer extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('acquirer');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '8',
             ));
        $this->hasColumn('bank_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '255',
             ));
        $this->hasColumn('acquirer_account', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '255',
             ));
        $this->hasColumn('acquirer_code', 'string', 64, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '64',
             ));
        $this->hasColumn('mcc_prefix', 'string', 7, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '7',
             ));
        $this->hasColumn('account_regex', 'string', 64, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '64',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Model_Merchant as Merchant', array(
             'local' => 'id',
             'foreign' => 'acquirer_id'));
    }
}