<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Model_Terminal', 'chinaums');

/**
 * Model_Base_Terminal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $merchant_id
 * @property string $terminal_no
 * @property Model_Merchant $Merchant
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author      <>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Terminal extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('terminal');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('merchant_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('terminal_no', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '8',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_Merchant as Merchant', array(
             'local' => 'merchant_id',
             'foreign' => 'id'));
    }
}