Acquirer:
  connection: chinaums
  tableName: acquirer
  columns:
    id:
      type: integer(8)
      primary: true
      autoincrement: true
    bank_name:
      type: string(255)
    acquirer_account:
      type: string(255)
    acquirer_code:
      type: string(64)
    mcc_prefix:
      type: string(7)
    account_regex:
      type: string(64)
  relations:
    Merchant:
      local: id
      foreign: acquirer_id
      type: many  
Merchant:
  connection: chinaums
  tableName: merchant
  columns:
    id:
      type: integer(8)
      primary: true
      autoincrement: true
    code:
      type: string(15)
      autoincrement: false
    name:
      type: string(255)
    address:
      type: string(255)
    legal_person:
      type: string(255)
    license_no:
      type: string(15)
    tax_no:
      type: string(20)
    id_card:
      type: string(18)
    contact:
      type: string(255)
    acquirer_id:
      type: integer(8)
    deposit_bank:
      type: string(255)
    account:
      type: string(255)
    mcc:
      type: string(4)
    rate:
      type: string(20)
    post:
      type: string(6)
    is_change_acquirer:
      type: boolean
    is_guarantee:
      type: boolean
    is_discount:
      type: boolean
    is_comfirm_risk:
      type: boolean
    is_close_creditcard:
      type: boolean
    create_date:
      type: date(25)
    send_date:
      type: date(25)
    receive_date:
      type: date(25)
    export_to_oss: 
      type: boolean
    export_to_unionpay:
      type: boolean
    upload_scan_file: 
      type: boolean
  relations:
    Acquirer:
      local: acquirer_id
      foreign: id
      type: one
    Terminal:
      local: id
      foreign: merchant_id
      type: many
   
Terminal:
  connection: chinaums
  tableName: terminal
  columns:
    id:
      type: integer(8)
      primary: true
      autoincrement: false
    merchant_id:
      type: integer(8)
    terminal_no:
      type: string(8)
  relations:
    Merchant:
      local: merchant_id
      foreign: id
      type: one
